announcement:
  pill: "Accepted"
  text: "CVPR 2026 Workshop in Denver, USA. CFP opens Jan 6, 2026 (AoE)."
contact_email: "grailworkshops@googlegroups.com"
brand:
  name: "GRAIL-V"
  subtitle: "CVPR 2026"
seo:
  og_image: "/assets/og-image.png"
hero:
  # eyebrow: "Grounded Retrieval and Agentic Intelligence for Vision-Language"
  # title: "Grounded evidence for vision-language agents"
  title: "Grounded Retrieval and Agentic Intelligence for Vision-Language"
  highlight: "plan > retrieve > rerank > verify"
  lead: "A CVPR 2026 workshop for researchers and practitioners building grounded multimodal retrieval, reranking, and verification systems that can be deployed with confidence."
  ctas:
    - label: "Submit Paper"
      href: "/cfp/#submit"
      style: "primary"
    - label: "Key Dates"
      href: "/cfp/#dates"
      style: "ghost"
    - label: "Contact"
      href: "mailto:grailworkshops@googlegroups.com?subject=GRAIL-V%20interest"
      style: "ghost"
  metrics:
    - value: "Who"
      label: "CV/IR/NLP/HCI researchers building grounded agents"
      href: "/topics/#topics"
    - value: "Format"
      label: "Keynotes 路 orals 路 posters/demos 路 panel"
      href: "/program/#program"
    - value: "Where"
      label: "Denver, USA 路 in-person + hybrid"
      href: "/venue/#venue"
    - value: "When"
      label: "Key dates and deadlines"
      href: "/cfp/#dates"
  countdowns:
    - label: "Submission deadline"
      text: "Mar 5, 2026 (AoE)"
      key: "submission"
    - label: "Workshop day"
      text: "Jun 3-4, 2026"
      key: "workshop"
loop:
  title: "P-R-R-V Loop"
  description: "Plan tasks and tool use, retrieve candidates, rerank with grounded reasoning, then verify with calibrated evidence."
  steps:
    - name: "Plan"
      key: "P"
      detail: "Agentic routing"
    - name: "Retrieve"
      key: "R"
      detail: "Hybrid search"
    - name: "Rerank"
      key: "R"
      detail: "Grounded scoring"
    - name: "Verify"
      key: "V"
      detail: "Evidence fidelity"
