announcement:
  pill: ""
  text: "CVPR 2026 Workshop in Denver, USA. CFP is now OPEN!"
contact_email: "grailworkshops@googlegroups.com"
brand:
  name: "GRAIL-V"
  subtitle: "CVPR 2026"
seo:
  og_image: "/assets/og-image.png"
  keywords:
    - "CVPR 2026"
    - "workshop"
    - "CVPR workshop"
    - "CVPR 2026 workshop"
    - "CVPR 2026 workshops"
    - "call for papers"
    - "CFP"
    - "workshop CFP"
    - "workshop call for papers"
    - "OpenReview"
    - "paper submission"
    - "camera-ready"
    - "workshop submissions"
    - "workshop proceedings"
    - "CVPR workshop proceedings"
    - "computer vision"
    - "vision-language models"
    - "VLM"
    - "multimodal AI"
    - "multimodal learning"
    - "information retrieval"
    - "IR"
    - "retrieval-augmented generation"
    - "RAG"
    - "dense retrieval"
    - "sparse retrieval"
    - "hybrid search"
    - "cross-encoder"
    - "reranking"
    - "grounding"
    - "provenance"
    - "citation"
    - "verification"
    - "calibration"
    - "benchmark"
    - "datasets"
    - "vision-language"
    - "multimodal retrieval"
    - "agentic AI"
    - "grounded retrieval"
    - "multimodal agents"
    - "reranking"
    - "evidence verification"
    - "vision-language workshop"
    - "multimodal workshop"
    - "retrieval workshop"
    - "agentic vision"
    - "grounded AI"
  event_start: "2026-06-03"
  event_end: "2026-06-04"
  event_location: "Denver, CO, USA"
hero:
  # eyebrow: "Grounded Retrieval and Agentic Intelligence for Vision-Language"
  # title: "Grounded evidence for vision-language agents"
  title: "Grounded Retrieval and Agentic Intelligence for Vision-Language"
  highlight: "plan > retrieve > reason > verify"
  lead: "A CVPR 2026 workshop for researchers and practitioners building grounded multimodal retrieval, reranking, and verification systems that can be deployed with confidence."
  ctas:
    - label: "Submit Paper"
      href: "/cfp/#submit"
      style: "primary"
    - label: "Key Dates"
      href: "/cfp/#dates"
      style: "ghost"
    - label: "Contact"
      href: "mailto:grailworkshops@googlegroups.com?subject=GRAIL-V%20interest"
      style: "ghost"
  metrics:
    - value: "Who"
      label: "CV, IR, NLP & HCI researchers advancing grounded multimodal retrieval, reasoning, and verification"
      href: "/topics/#topics"
    - value: "Format"
      label: "Invited keynotes · oral presentations · poster & demo sessions · expert panel discussion"
      href: "/program/#program"
    - value: "Where"
      label: "CVPR 2026 · Denver, CO, USA · in-person with hybrid access"
      href: "/venue/#venue"
    - value: "When"
      label: "Jun 3–4, 2026 · Submissions due Mar 5 (AoE)"
      href: "/cfp/#dates"
  countdowns:
    - label: "Submission deadline"
      text: "Mar 5, 2026 (AoE)"
      key: "submission"
    - label: "Workshop day"
      text: "Jun 3-4, 2026"
      key: "workshop"
loop:
  title: "P-R-R-V Loop"
  description: "Plan tasks and tool use, retrieve candidates, rerank with grounded reasoning, then verify with calibrated evidence."
  steps:
    - name: "Plan"
      key: "P"
      detail: "Agentic Planning & Routing across generative multimodal models"
    - name: "Retrieve"
      key: "R"
      detail: "Multimodal Retrieval and Reranking across structured and unstructured knowledge sources"
    - name: "Reason"
      key: "R"
      detail: "Grounded multimodal reasoning using tool-use, augemented generations, generative editing, and temporal video orchestration"
    - name: "Verify"
      key: "V"
      detail: "Calibrated verification via citation provenance, metric design, and rigorous benchmark curation"
