announcement:
  pill: "Accepted"
  text: "CVPR 2026 Workshop in Denver, USA. CFP opens Jan 6, 2026 (AoE)."
brand:
  name: "GRAIL-V"
  subtitle: "CVPR 2026"
seo:
  og_image: "/assets/og-image.png"
hero:
  eyebrow: "Grounded Retrieval and Agentic Intelligence for Vision-Language"
  title: "GRAIL-V puts evidence at the center of"
  highlight: "plan, retrieve, rerank, verify"
  lead: "A CVPR 2026 workshop dedicated to grounded multimodal retrieval, reranking, and verification for agentic vision systems across images, video, documents, charts, and UI."
  ctas:
    - label: "Submit Paper"
      href: "/cfp/#submit"
      style: "primary"
    - label: "Read the Proposal"
      href: "/files/GRAIL_WORKSHOP_CVPR_Accepted.pdf"
      style: "ghost"
    - label: "Join Mailing List"
      href: "mailto:amit.h.agarwal@oracle.com?subject=GRAIL-V%20interest"
      style: "ghost"
  metrics:
    - value: "100-300"
      label: "Expected attendees"
      href: "/venue/#venue"
    - value: "4"
      label: "Keynotes"
      href: "/speakers/#speakers"
    - value: "2"
      label: "Oral sessions"
      href: "/program/#program"
    - value: "2"
      label: "Poster and demo blocks"
      href: "/program/#program"
  countdowns:
    - label: "Submission deadline"
      text: "Mar 5, 2026 (AoE)"
      key: "submission"
    - label: "Workshop day"
      text: "Jun 3-4, 2026"
      key: "workshop"
loop:
  title: "P-R-R-V Loop"
  description: "Plan tasks and tool use, retrieve candidates, rerank with grounded reasoning, then verify with calibrated evidence."
  steps:
    - name: "Plan"
      key: "P"
      detail: "Agentic routing"
    - name: "Retrieve"
      key: "R"
      detail: "Hybrid search"
    - name: "Rerank"
      key: "R"
      detail: "Grounded scoring"
    - name: "Verify"
      key: "V"
      detail: "Evidence fidelity"
